#include<iostream>
#include<stdlib.h>
#include<windows.h>
using namespace std;
int main()
{
	cout<<"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t\t\t\t\t\tGiao牌蹦迪机";
	system("color 01");
	Sleep(100);
	system("color 02");
	Sleep(100);
	system("color 03");
	Sleep(100);
	system("color 04");
	Sleep(100);
	system("color 05");
	Sleep(100);
	system("color 06");
	Sleep(100);
	system("color 07");
	Sleep(100);
	system("color 08");
	Sleep(100);
	system("color 09");
	Sleep(100);
	system("color 0a");
	Sleep(100);
	system("color 0b");
	Sleep(100);
	system("color 0c");
	Sleep(100);
	system("color 0d");
	Sleep(100);
	system("color 0e");
	Sleep(100);
	system("color 0f");
	Sleep(100);
		system("color 10");
		Sleep(100);
		system("color 12");
		Sleep(100);
		system("color 13");
		Sleep(100);
		system("color 14");
		Sleep(100);
		system("color 15");
		Sleep(100);
		system("color 16");
		Sleep(100);
		system("color 17");
		Sleep(100);
		system("color 18");
		Sleep(100);
		system("color 19");
		Sleep(100);
		system("color 1a");
		Sleep(100);
		system("color 1b");
		Sleep(100);
		system("color 1c");
		Sleep(100);
		system("color 1d");
		Sleep(100);
		system("color 1e");
		Sleep(100);
		system("color 1f");
		Sleep(100);
			system("color 20");
			Sleep(100);
			system("color 21");
			Sleep(100);
			system("color 23");
			Sleep(100);
			system("color 24");
			Sleep(100);
			system("color 25");
			Sleep(100);
			system("color 26");
			Sleep(100);
			system("color 27");
			Sleep(100);
			system("color 28");
			Sleep(100);
			system("color 29");
			Sleep(100);
			system("color 2a");
			Sleep(100);
			system("color 2b");
			Sleep(100);
			system("color 2c");
			Sleep(100);
			system("color 2d");
			Sleep(100);
			system("color 2e");
			Sleep(100);
			system("color 2f");
			Sleep(100);
				system("color 30");
				Sleep(100);
				system("color 31");
				Sleep(100);
				system("color 32");
				Sleep(100);
				system("color 34");
				Sleep(100);
				system("color 35");
				Sleep(100);
				system("color 36");
				Sleep(100);
				system("color 37");
				Sleep(100);
				system("color 38");
				Sleep(100);
				system("color 39");
				Sleep(100);
				system("color 3a");
				Sleep(100);
				system("color 3b");
				Sleep(100);
				system("color 3c");
				Sleep(100);
				system("color 3d");
				Sleep(100);
				system("color 3e");
				Sleep(100);
				system("color 3f");
				Sleep(100);
					system("color 40");
					Sleep(100);
					system("color 41");
					Sleep(100);
					system("color 42");
					Sleep(100);
					system("color 43");
					Sleep(100);
					system("color 45");
					Sleep(100);
					system("color 46");
					Sleep(100);
					system("color 47");
					Sleep(100);
					system("color 48");
					Sleep(100);
					system("color 49");
					Sleep(100);
					system("color 4a");
					Sleep(100);
					system("color 4b");
					Sleep(100);
					system("color 4c");
					Sleep(100);
					system("color 4d");
					Sleep(100);
					system("color 4e");
					Sleep(100);
					system("color 4f");
					Sleep(100);
						system("color 50");
						Sleep(100);
						system("color 51");
						Sleep(100);
						system("color 52");
						Sleep(100);
						system("color 53");
						Sleep(100);
						system("color 54");
						Sleep(100);
						system("color 56");
						Sleep(100);
						system("color 57");
						Sleep(100);
						system("color 58");
						Sleep(100);
						system("color 59");
						Sleep(100);
						system("color 5a");
						Sleep(100);
						system("color 5b");
						Sleep(100);
						system("color 5c");
						Sleep(100);
						system("color 5d");
						Sleep(100);
						system("color 5e");
						Sleep(100);
						system("color 5f");
						Sleep(100);
						system("color 60");
						Sleep(100);
						system("color 61");
						Sleep(100);
						system("color 62");
						Sleep(100);
						system("color 63");
						Sleep(100);
						system("color 64");
						Sleep(100);
						system("color 65");
						Sleep(100);
						system("color 67");
						Sleep(100);
						system("color 68");
						Sleep(100);
						system("color 69");
						Sleep(100);
						system("color 6a");
						Sleep(100);
						system("color 6b");
						Sleep(100);
						system("color 6c");
						Sleep(100);
						system("color 6d");
						Sleep(100);
						system("color 6e");
						Sleep(100);
						system("color 6f");
						Sleep(100);
							system("color 70");
							Sleep(100);
							system("color 71");
							Sleep(100);
							system("color 72");
							Sleep(100);
							system("color 73");
							Sleep(100);
							system("color 74");
							Sleep(100);
							system("color 75");
							Sleep(100);
							system("color 76");
							Sleep(100);
							system("color 78");
							Sleep(100);
							system("color 79");
							Sleep(100);
							system("color 7a");
							Sleep(100);
							system("color 7b");
							Sleep(100);
							system("color 7c");
							Sleep(100);
							system("color 7d");
							Sleep(100);
							system("color 7e");
							Sleep(100);
							system("color 7f");
							Sleep(100);
								system("color 80");
								Sleep(100);
								system("color 81");
								Sleep(100);
								system("color 82");
								Sleep(100);
								system("color 83");
								Sleep(100);
								system("color 84");
								Sleep(100);
								system("color 85");
								Sleep(100);
								system("color 86");
								Sleep(100);
								system("color 87");
								Sleep(100);
								system("color 89");
								Sleep(100);
								system("color 8a");
								Sleep(100);
								system("color 8b");
								Sleep(100);
								system("color 8c");
								Sleep(100);
								system("color 8d");
								Sleep(100);
								system("color 8e");
								Sleep(100);
								system("color 8f");
								Sleep(100);
								system("color 90");
								Sleep(100);
								system("color 91");
								Sleep(100);
								system("color 92");
								Sleep(100);
								system("color 93");
								Sleep(100);
								system("color 94");
								Sleep(100);
								system("color 95");
								Sleep(100);
								system("color 96");
								Sleep(100);
								system("color 97");
								Sleep(100);
								system("color 98");
								Sleep(100);
								system("color 9a");
								Sleep(100);
								system("color 9b");
								Sleep(100);
								system("color 9c");
								Sleep(100);
								system("color 9d");
								Sleep(100);
								system("color 9e");
								Sleep(100);
								system("color 9f");
								Sleep(100);
								system("color a0");
								Sleep(100);
								system("color a1");
								Sleep(100);
								system("color a2");
								Sleep(100);
								system("color a3");
								Sleep(100);
								system("color a4");
								Sleep(100);
								system("color a5");
								Sleep(100);
								system("color a6");
								Sleep(100);
								system("color a7");
								Sleep(100);
								system("color a8");
								Sleep(100);
								system("color a9");
								Sleep(100);
								system("color ab");
								Sleep(100);
								system("color ac");
								Sleep(100);
								system("color ad");
								Sleep(100);
								system("color ae");
								Sleep(100);
								system("color af");
								Sleep(100);

								system("color b0");
								Sleep(100);
								system("color b1");
								Sleep(100);
								system("color b2");
								Sleep(100);
								system("color b3");
								Sleep(100);
								system("color b4");
								Sleep(100);
								system("color b5");
								Sleep(100);
								system("color b6");
								Sleep(100);
								system("color b7");
								Sleep(100);
								system("color b8");
								Sleep(100);
								system("color b9");
								Sleep(100);
								system("color ba");
								Sleep(100);
								system("color bc");
								Sleep(100);
								system("color bd");
								Sleep(100);
								system("color be");
								Sleep(100);
								system("color bf");
								Sleep(100);

								system("color c0");
								Sleep(100);
								system("color c1");
								Sleep(100);
								system("color c2");
								Sleep(100);
								system("color c3");
								Sleep(100);
								system("color c4");
								Sleep(100);
								system("color c5");
								Sleep(100);
								system("color c6");
								Sleep(100);
								system("color c7");
								Sleep(100);
								system("color c8");
								Sleep(100);
								system("color c9");
								Sleep(100);
								system("color ca");
								Sleep(100);
								system("color cb");
								Sleep(100);
								system("color cd");
								Sleep(100);
								system("color ce");
								Sleep(100);
								system("color cf");
								Sleep(100);

								system("color d0");
								Sleep(100);
								system("color d1");
								Sleep(100);
								system("color d2");
								Sleep(100);
								system("color d3");
								Sleep(100);
								system("color d4");
								Sleep(100);
								system("color d5");
								Sleep(100);
								system("color d6");
								Sleep(100);
								system("color d7");
								Sleep(100);
								system("color d8");
								Sleep(100);
								system("color d9");
								Sleep(100);
								system("color da");
								Sleep(100);
								system("color db");
								Sleep(100);
								system("color dc");
								Sleep(100);
								system("color de");
								Sleep(100);
								system("color df");
								Sleep(100);

								system("color e0");
								Sleep(100);
								system("color e1");
								Sleep(100);
								system("color e2");
								Sleep(100);
								system("color e3");
								Sleep(100);
								system("color e4");
								Sleep(100);
								system("color e5");
								Sleep(100);
								system("color e6");
								Sleep(100);
								system("color e7");
								Sleep(100);
								system("color e8");
								Sleep(100);
								system("color e9");
								Sleep(100);
								system("color ea");
								Sleep(100);
								system("color eb");
								Sleep(100);
								system("color ec");
								Sleep(100);
								system("color ed");
								Sleep(100);
								system("color ef");
								Sleep(100);

								system("color f0");
								Sleep(100);
								system("color f1");
								Sleep(100);
								system("color f2");
								Sleep(100);
								system("color f3");
								Sleep(100);
								system("color f4");
								Sleep(100);
								system("color f5");
								Sleep(100);
								system("color f6");
								Sleep(100);
								system("color f7");
								Sleep(100);
								system("color f8");
								Sleep(100);
								system("color f9");
								Sleep(100);
								system("color fa");
								Sleep(100);
								system("color fb");
								Sleep(100);
								system("color fc");
								Sleep(100);
								system("color fd");
								Sleep(100);
								system("color fe");
								Sleep(100);
	system("cls");
	system("color 07");		
	return 0;
}
